version: '3.8'

services:
  web:
    build: .
    working_dir: /app
    restart: always
    command: sh -c "python manage.py migrate --noinput && gunicorn hackshield.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./:/app
      - media:/app/media
      - keys:/app/keys
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - broker

  worker:
    build: .
    working_dir: /app
    restart: always
    command: celery -A hackshield.celery_app worker --loglevel=info
    volumes:
      - ./:/app
      - media:/app/media
      - keys:/app/keys
    env_file:
      - .env
    depends_on:
      - broker

  broker:
    image: redis:6-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  media:
  keys:
  redis_data:
